packages:
  # Just Internal
  - "dev"
  # Preview / Dev / Debug
  - "packages/codemirror/*/dev"
  # Tests, obvs
  - "packages/codemirror/*/tests"
  - "packages/glimdown/*/tests"
  # Potentially publishables
  - "packages/*"
  - "packages/glimdown/*"
  - "packages/remark/*"
  - "packages/lezer/*"
  - "packages/lezer/*/*"
  - "packages/codemirror/*"
