export const Comment: 2,
  HtmlComment: 5,
  LongComment: 4,
  MoustacheExpression: 6,
  SExpression: 8,
  ShortComment: 3,
  String: 9,
  Template: 1,
  attributeValueContentDouble: 10,
  attributeValueContentSingle: 11,
  htmlCommentContent: 50,
  longCommentContent: 49,
  shortCommentContent: 48,
  templateTagContent: 55;
