name: CI
on:
  pull_request:
  push:
    branches: [main]

##############################################################

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

env:
  TURBO_API: 'http://127.0.0.1:9080'
  TURBO_TOKEN: 'not-a-secret'
  TURBO_TEAM: 'foo'

##############################################################

jobs:

  install_dependencies:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: wyvox/action@v1 

##############################################################

  lints:
    name: "Lints"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install_dependencies]

    steps:
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: wyvox/action@v1 
      - run: pnpm lint

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install_dependencies]

    steps:
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: wyvox/action@v1 
      - run: pnpm test

